### ISSUE TITLE
Is "scheduler-kind-configuration-is-avail" useful?

### ISSUE THREAD

**Issue by michbin** [openBackhaul/schedulerProfile#1]
Does the `scheduler-kind-configuration-is-avail` leaf in the `scheduler-profile-capability` grouping/container make sense at all?
Can a scheduler profile be created without setting the scheduler kind per queue?

**Comment by openBackhaul** [comment]
**Discussion on DMIP call on 19.05.2022:**
Yes, it's true. It could also be seen from availableSchedulingKindList containing only a single entry for all the queues, if a profile would not allow configuring the schedulerKind.
There is no concrete preference, whether to keep or remove the SchedulerProfileCapability :: schedulerKindConfigurationIsAvail attribute.
.
**Proposal to the 5G-xhaul call on 1st of June 2022:**
Keeping the SchedulerProfileCapability :: schedulerKindConfigurationIsAvail attribute as is, because it spares looking through all queues' availableSchedulingKindList to realized that configuring the schedulerKind is available, or not.

**Comment by demx8as6** [comment]
Decision made at  the 5G-xhaul call on 1st of June 2022 to close this issues, because there is no change on UML or YANG needed. @openBackhaul: Please close the issue.
